research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given the current year is {current_year}.
  expected_output: >
    A list with 10 detailed bullet points of the most relevant information about {topic}, including how they relate to each other.
  agent: planner

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    1. A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
    2. Prioritize the latest trends, key players, and noteworthy news on {topic}.
    3. Identify the target audience, considering their interests and pain points.
    4. Develop a detailed content outline including an introduction, key points, and a call to action.
    5. Include SEO keywords and relevant data or sources.
  agent: reporting_analyst

writing_task:
  description: >
    1. Write a blog post about {topic} based on the report you received.
    2. Incorporate SEO keywords naturally.
    3. Sections/Subtitles are properly named and structured.
    4. Ensure the post is structured with an engaging introduction, insightful body, and a summarizing conclusion.
    5. Proofread for grammatical errors and alignment with the brand's voice.
    Make sure the blog post is engaging, informative, and easy to read.
  expected_output: >
    A blog post of 1000 words or more that covers the main topics in the report.
    The blog post should be engaging, informative, and easy to read.
  agent: writer

editing_task:
  description: >
    1. Review the blog post you received and provide feedback on how to improve it.
    2. Ensure the content is accurate, engaging, and on-brand.
    3. Make sure the blog post is well-structured and easy to read.
    4. Provide suggestions for improvement, including additional information or clarifications.
    5. Ensure the blog post is free of grammatical errors and typos.
  expected_output: >
    A revised blog post that incorporates the feedback provided.
  agent: editor